### ISSUE TITLE
Base setup of project

### ISSUE THREAD

**Issue by EdelCorbett** [EdelCorbett/the-pool-hall#10]
[Epic: 1 ](https://github.com/EdelCorbett/the-pool-hall/milestone/3)

As a  **Developer** I can **setup a project** so that **begin project**

**Acceptance Criteria**
1. Create a Django project 
2. Create the base structure of the project

**Tasks**
- [x] Create  virtual environment 
- [x] Install Django and gunicorn
- [x] Install psycopg2
- [x] Install Whitenoise for static files
- [x] Start Django project
- [x] Create App name and add to INSTALLED APPS in settings.py
- [x] Create env.py and .gitignore files
- [x] Add secret keys to env.py 
- [x] Add env.py to .gitignore file
- [x] Create requirements.txt file

**Comment by EdelCorbett** [comment]
The base setup of project complied.
