### ISSUE TITLE
Deployment to Heroku

### ISSUE THREAD

**Issue by EdelCorbett** [EdelCorbett/the-pool-hall#12]
[Epic: 1 ](https://github.com/EdelCorbett/the-pool-hall/milestone/3 )

As a **Developer** I can **Deploy project early** so that **I can continually test the application during development**

**Acceptance Criteria**
Deployed application on Heroku

**Task**
- [x] Create new app in Heroku
- [x] Add config vars in settings
- [x] Add heroku app to allowed host in settings.py
- [x] Create Procfile  for gunicorn
- [x] Add requirments.txt
- [x] Deploy to heroku

**Comment by EdelCorbett** [comment]
Deployment completed .
