### ISSUE TITLE
Form Design

### ISSUE THREAD

**Issue by EdelCorbett** [EdelCorbett/the-pool-hall#18]
[Epic: 4 ]( https://github.com/EdelCorbett/the-pool-hall/issues/5)

As a **User** I can **clearly determine what each form is for** so that **correctly fill them out**

**Acceptance Criteria**
All forms are clearly labeled
All form have similar design 
All form have clear instructions

**Task**
- [x] Create form design 
- [x] ensure all form are clear
- [x] have date picker 
- [x] have drop down time options
