### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by EdelCorbett** [EdelCorbett/the-pool-hall#19]
[Epic: 4]( https://github.com/EdelCorbett/the-pool-hall/issues/5)

As a **Developer** I can **design a clear footer with social link and business information**so that**The user can use link and find business info easy**

**Acceptance Criteria**
Clear footer with business info and clickable links to social media

**Task**
- [x] Create footer design 
- [x] Create social links 
- [x] Make social link active
