### ISSUE TITLE
Booking

### ISSUE THREAD

**Issue by EdelCorbett** [EdelCorbett/the-pool-hall#3]
[Epic: 3](https://github.com/EdelCorbett/the-pool-hall/milestone/2)

As a **users** I can **choose time** so that **make a reservation**

**Acceptance Criteria**
1. A booking form so user can make a booking
2. Display available times 
3. Display available Date

**Tasks**
- [x] Create booking form
- [x] Add a date picker 
- [x] Drop down menu with available times
