### ISSUE TITLE
Event

### ISSUE THREAD

**Issue by EdelCorbett** [EdelCorbett/the-pool-hall#6]
[Epic: ]( )

As a **user** I can **view up coming events** so that **I know whats coming up and i can comment and like the posts**

**Acceptance Criteria**
1. Event section with upcoming event
2. Event details
3. Users can comment and like on events
4. Users can edit and delete their comments

**TASKS**
- [x] Create post page
- [x] Create comment section
- [x] Create like button
- [x] Create edit button
- [x] Create delete button
